# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 464d2c925f063882100fe3e058c035e169e44ec04b356c49e7659016b82b398ba449a6032072ce5a2bf290079ab234c686d906566870c319af59deb04efc676b

test:
  secret_key_base: 94f287e4dd5e9bd6194a42ecdf115bee3ad608cc440706db5a4614bc14c12e5a395924a16cde346db7c729accf2dc3c1b99a58ee8743227adeec1eed268f158c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
